server {
    listen 80;
    server_name app.localhost.com api.localhost.com;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name app.localhost.com;
    client_max_body_size 25m;

    ssl_certificate     /etc/nginx/local/app.localhost.com.pem;
    ssl_certificate_key /etc/nginx/local/app.localhost.com-key.pem;

    location /api/ {
        proxy_set_header Host api.localhost.com;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        proxy_pass http://operator-api:3001/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://operator-ui:80;
    }
}

server {
    listen 443 ssl;
    server_name api.localhost.com;
    client_max_body_size 25m;

    ssl_certificate     /etc/nginx/local/app.localhost.com.pem;
    ssl_certificate_key /etc/nginx/local/app.localhost.com-key.pem;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        proxy_pass http://operator-api:3001;
    }
}
