ALTER TABLE "core"."MarketProfile"
ADD COLUMN "geo_mode" TEXT NOT NULL DEFAULT 'COUNTRY',
ADD COLUMN "geo_targets" TEXT[] NOT NULL DEFAULT ARRAY['MY']::TEXT[],
ADD COLUMN "geo_strictness" TEXT NOT NULL DEFAULT 'BALANCED';
