server {
    listen 80;
    server_name app.syntrae.ai;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name app.syntrae.ai;

    ssl_certificate /etc/letsencrypt/live/syntrae.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/syntrae.ai/privkey.pem;

    include /etc/nginx/proxy_params;

    location / {
        proxy_pass http://operator-ui:80;
    }
}
