server {
    listen 80;
    server_name localhost;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/letsencrypt/live/syntraeai.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/syntraeai.com/privkey.pem;

    include /etc/nginx/proxy_params;

    location / {
        proxy_pass http://operator-ui:80;
    }

    location /api/ {
        proxy_pass http://operator-api:3001/;
    }
}
