server {
    listen 80;
    server_name localhost;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name localhost;
    client_max_body_size 25m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    ssl_certificate /etc/letsencrypt/live/app.syntraeai.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.syntraeai.com/privkey.pem;

    include /etc/nginx/proxy_params;

     location / {
       set $operator_ui_upstream http://operator-ui:80;
       proxy_pass $operator_ui_upstream;
    }

    location /api/ {
        set $operator_api_upstream http://operator-api:3001;
        rewrite ^/api/?(.*)$ /$1 break;
        proxy_pass $operator_api_upstream;
    }
}
