server {
    listen 80;
    server_name syntraeai.com www.syntraeai.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    if ($host = www.syntraeai.com) {
        return 301 https://syntraeai.com$request_uri;
    }

    location / {
        proxy_pass http://marketing-ui:80;
        include /etc/nginx/proxy_params;
    }
}

server {
    listen 443 ssl;
    server_name syntraeai.com www.syntraeai.com;
   
    ssl_certificate /etc/letsencrypt/live/app.syntraeai.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.syntraeai.com/privkey.pem;

    if ($host = www.syntraeai.com) {
        return 301 https://syntraeai.com$request_uri;
    }

    location / {
        proxy_pass http://marketing-ui:80;
        include /etc/nginx/proxy_params;
    }
}
