server {
    listen 80;
    server_name syntraeai.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://app.syntraeai.com;
    }
}

server {
    listen 443 ssl;
    server_name syntraeai.com;
    
    ssl_certificate /etc/letsencrypt/live/app.syntraeai.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.syntraeai.com/privkey.pem;
    location / {
        return 301 https://app.syntraeai.com;
    }
}
