import logging
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional

from video_engine.core.schemas import InputData, DetectionResult, ModelConfig, EmbeddingsBundle
from video_engine.engine import VideoDetectionEngine

router = APIRouter()

# Initialize Engine (Singleton per worker essentially)
# Config should come from env or default
config = ModelConfig() 
engine = VideoDetectionEngine(config=config)

logger = logging.getLogger(__name__)

class DetectWithBundleRequest(BaseModel):
    data: InputData
    bundle: EmbeddingsBundle

@router.post("/", response_model=DetectionResult)
async def detect(data: InputData):
    """
    Run detection on pre-ingested InputData.
    The Engine will generate the embeddings internally (using cache if enabled).
    """
    try:
        # Phase 3: We can optionally accept a bundle if the client already has it,
        # but InputData implies we start from ingestion output.
        # The Engine will generate the bundle internally.
        
        result = engine.process(data)
        return result
        
    except Exception as e:
        logger.error(f"Detection failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/with_bundle", response_model=DetectionResult)
async def detect_with_bundle(request: DetectWithBundleRequest):
    """
    Run detection using provided EmbeddingsBundle + InputData.
    Useful if Embeddings were generated by a separate service.
    """
    try:
        result = engine.process(request.data, request.bundle)
        return result
    except Exception as e:
        logger.error(f"Detection failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))
